"""changed name of column in images table to 'url' from 'image_url'

Revision ID: f965a959edd8
Revises: d7ad6dd6b516
Create Date: 2022-06-04 19:23:05.761832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f965a959edd8'
down_revision = 'd7ad6dd6b516'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('url', sa.String(length=255), nullable=False))
    op.drop_column('images', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('image_url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('images', 'url')
    # ### end Alembic commands ###
