"""updated post model

Revision ID: d7ad6dd6b516
Revises: 197acc8d4353
Create Date: 2022-06-04 08:55:59.720061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7ad6dd6b516'
down_revision = '197acc8d4353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_category_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('posts_category_id_fkey', 'posts', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
